# Enter the directory path for the project you want to migrate and the output directory path

github_username: "username"
github_token: "token"
git_branch: "migrated_code"
repo_name: "repo_name"
commit_message: "code migrated"

entry_path: "/path/to/project"
output_path: "./path/to/output"

legacy_language: python # change this (This is the language & framework that we use for documentation)
legacy_framework: flask # change this 

new_language: rust # change this (comming soon!)
new_framework: actix web # change this (comming soon!)

langchain_tracing: false
langchain_verbose: false

thread_id: 0001 # This is required for the frontend (comming soon!)

document: 
  model: 
    name: gpt-4o-mini

dir_struct: 
  model: 
    name: gpt-4o

planner: 
  model: 
    name: gpt-4o-mini